"""
53 Python Coding Challenges
Progressive difficulty from beginner to advanced
No hints - users can purchase AI hints instead
"""

LEVELS = [
    # BEGINNER (1-10): Basic syntax and concepts
    {
        'title': 'Hello World',
        'slug': 'level-1',
        'description': 'Print "Hello, World!" to the console.',
        'initial_code': '# Write your code here\n',
        'test_code': 'assert output.strip() == "Hello, World!"',
        'order': 1,
        'xp_reward': 50,
        'target_time_seconds': 180,  # 3 minutes
    },
    {
        'title': 'Simple Math',
        'slug': 'level-2',
        'description': 'Calculate and print the sum of 5 + 3.',
        'initial_code': '# Calculate 5 + 3\n',
        'test_code': 'assert output.strip() == "8"',
        'order': 2,
        'xp_reward': 50,
        'target_time_seconds': 180,
    },
    {
        'title': 'Variables',
        'slug': 'level-3',
        'description': 'Create a variable `name` with your name and print "Hello, [name]!"',
        'initial_code': 'name = ""\n',
        'test_code': 'assert "Hello," in output and name in output',
        'order': 3,
        'xp_reward': 50,
        'target_time_seconds': 240,
    },
    {
        'title': 'String Concatenation',
        'slug': 'level-4',
        'description': 'Combine two strings "Python" and "Rocks" with a space and print the result.',
        'initial_code': 'word1 = "Python"\nword2 = "Rocks"\n',
        'test_code': 'assert output.strip() == "Python Rocks"',
        'order': 4,
        'xp_reward': 50,
        'target_time_seconds': 240,
    },
    {
        'title': 'User Input',
        'slug': 'level-5',
        'description': 'Create a variable `age` and print "You are [age] years old"',
        'initial_code': 'age = 25\n',
        'test_code': 'assert "You are" in output and str(age) in output',
        'order': 5,
        'xp_reward': 50,
        'target_time_seconds': 300,
    },
    {
        'title': 'If Statement',
        'slug': 'level-6',
        'description': 'Create a variable `score` and print "Pass" if score >= 50, else print "Fail"',
        'initial_code': 'score = 75\n',
        'test_code': 'score = 60\nexec(user_code)\nassert "Pass" in output\nscore = 40\noutput = ""\nexec(user_code)\nassert "Fail" in output',
        'order': 6,
        'xp_reward': 50,
        'target_time_seconds': 360,
    },
    {
        'title': 'For Loop',
        'slug': 'level-7',
        'description': 'Use a for loop to print numbers from 1 to 5.',
        'initial_code': '# Print 1 to 5\n',
        'test_code': 'lines = output.strip().split("\\n")\nassert len(lines) == 5\nassert all(str(i+1) in lines[i] for i in range(5))',
        'order': 7,
        'xp_reward': 50,
        'target_time_seconds': 360,
    },
    {
        'title': 'While Loop',
        'slug': 'level-8',
        'description': 'Use a while loop to count from 1 to 3.',
        'initial_code': 'count = 1\n',
        'test_code': 'assert "1" in output and "2" in output and "3" in output',
        'order': 8,
        'xp_reward': 50,
        'target_time_seconds': 360,
    },
    {
        'title': 'List Creation',
        'slug': 'level-9',
        'description': 'Create a list with numbers [1, 2, 3, 4, 5] and print it.',
        'initial_code': 'numbers = []\n',
        'test_code': 'assert numbers == [1, 2, 3, 4, 5]',
        'order': 9,
        'xp_reward': 50,
        'target_time_seconds': 300,
    },
    {
        'title': 'List Access',
        'slug': 'level-10',
        'description': 'Print the first and last element of the list [10, 20, 30, 40, 50].',
        'initial_code': 'numbers = [10, 20, 30, 40, 50]\n',
        'test_code': 'assert "10" in output and "50" in output',
        'order': 10,
        'xp_reward': 50,
        'target_time_seconds': 300,
    },
    
    # EASY-INTERMEDIATE (11-25): Functions, data structures
    {
        'title': 'Define a Function',
        'slug': 'level-11',
        'description': 'Define a function `greet()` that prints "Hello!"',
        'initial_code': 'def greet():\n    pass\n\ngreet()\n',
        'test_code': 'assert "Hello!" in output',
        'order': 11,
        'xp_reward': 50,
        'target_time_seconds': 420,
    },
    {
        'title': 'Function with Parameters',
        'slug': 'level-12',
        'description': 'Define a function `add(a, b)` that returns the sum of a and b. Print add(3, 7).',
        'initial_code': 'def add(a, b):\n    pass\n',
        'test_code': 'result = add(3, 7)\nassert result == 10',
        'order': 12,
        'xp_reward': 50,
        'target_time_seconds': 420,
    },
    {
        'title': 'Return Values',
        'slug': 'level-13',
        'description': 'Create a function `square(n)` that returns n squared. Print square(5).',
        'initial_code': 'def square(n):\n    pass\n',
        'test_code': 'assert square(5) == 25\nassert square(3) == 9',
        'order': 13,
        'xp_reward': 50,
        'target_time_seconds': 420,
    },
    {
        'title': 'List Iteration',
        'slug': 'level-14',
        'description': 'Loop through the list [1, 2, 3] and print each number multiplied by 2.',
        'initial_code': 'numbers = [1, 2, 3]\n',
        'test_code': 'assert "2" in output and "4" in output and "6" in output',
        'order': 14,
        'xp_reward': 50,
        'target_time_seconds': 480,
    },
    {
        'title': 'Dictionary Basics',
        'slug': 'level-15',
        'description': 'Create a dictionary with keys "name" and "age", and print the name.',
        'initial_code': 'person = {}\n',
        'test_code': 'assert "name" in person and "age" in person',
        'order': 15,
        'xp_reward': 50,
        'target_time_seconds': 480,
    },
    {
        'title': 'Sum of List',
        'slug': 'level-16',
        'description': 'Calculate and print the sum of [1, 2, 3, 4, 5].',
        'initial_code': 'numbers = [1, 2, 3, 4, 5]\n',
        'test_code': 'assert "15" in output',
        'order': 16,
        'xp_reward': 50,
        'target_time_seconds': 480,
    },
    {
        'title': 'Max in List',
        'slug': 'level-17',
        'description': 'Find and print the maximum number in [3, 7, 2, 9, 1].',
        'initial_code': 'numbers = [3, 7, 2, 9, 1]\n',
        'test_code': 'assert "9" in output',
        'order': 17,
        'xp_reward': 50,
        'target_time_seconds': 480,
    },
    {
        'title': 'String Reversal',
        'slug': 'level-18',
        'description': 'Reverse the string "Python" and print it.',
        'initial_code': 'text = "Python"\n',
        'test_code': 'assert "nohtyP" in output',
        'order': 18,
        'xp_reward': 50,
        'target_time_seconds': 540,
    },
    {
        'title': 'Count Vowels',
        'slug': 'level-19',
        'description': 'Count and print the number of vowels in "Hello World".',
        'initial_code': 'text = "Hello World"\n',
        'test_code': 'assert "3" in output',
        'order': 19,
        'xp_reward': 50,
        'target_time_seconds': 600,
    },
    {
        'title': 'Even Numbers',
        'slug': 'level-20',
        'description': 'Print all even numbers from 1 to 10.',
        'initial_code': '# Print even numbers\n',
        'test_code': 'assert "2" in output and "4" in output and "6" in output and "8" in output and "10" in output',
        'order': 20,
        'xp_reward': 50,
        'target_time_seconds': 540,
    },
    {
        'title': 'Factorial',
        'slug': 'level-21',
        'description': 'Calculate the factorial of 5 (5! = 120).',
        'initial_code': 'n = 5\n',
        'test_code': 'assert "120" in output',
        'order': 21,
        'xp_reward': 50,
        'target_time_seconds': 600,
    },
    {
        'title': 'Palindrome Check',
        'slug': 'level-22',
        'description': 'Check if "radar" is a palindrome. Print True or False.',
        'initial_code': 'word = "radar"\n',
        'test_code': 'assert "True" in output',
        'order': 22,
        'xp_reward': 50,
        'target_time_seconds': 600,
    },
    {
        'title': 'FizzBuzz Light',
        'slug': 'level-23',
        'description': 'Print "Fizz" if a number is divisible by 3, else print the number. Test with 9.',
        'initial_code': 'num = 9\n',
        'test_code': 'num = 9\nexec(user_code)\nassert "Fizz" in output\nnum = 7\noutput = ""\nexec(user_code)\nassert "7" in output',
        'order': 23,
        'xp_reward': 50,
        'target_time_seconds': 600,
    },
    {
        'title': 'Remove Duplicates',
        'slug': 'level-24',
        'description': 'Remove duplicates from [1, 2, 2, 3, 4, 4, 5] and print the unique list.',
        'initial_code': 'numbers = [1, 2, 2, 3, 4, 4, 5]\n',
        'test_code': 'assert len(set(numbers)) == 5',
        'order': 24,
        'xp_reward': 50,
        'target_time_seconds': 600,
    },
    {
        'title': 'List Comprehension',
        'slug': 'level-25',
        'description': 'Use list comprehension to create a list of squares from 1 to 5.',
        'initial_code': '# Create [1, 4, 9, 16, 25]\n',
        'test_code': 'assert [1, 4, 9, 16, 25] in str(output) or "squares" in dir() and squares == [1, 4, 9, 16, 25]',
        'order': 25,
        'xp_reward': 50,
        'target_time_seconds': 660,
    },
    
    # INTERMEDIATE (26-40): Algorithms, problem solving
    {
        'title': 'Prime Number',
        'slug': 'level-26',
        'description': 'Check if 17 is a prime number. Print True or False.',
        'initial_code': 'n = 17\n',
        'test_code': 'assert "True" in output',
        'order': 26,
        'xp_reward': 50,
        'target_time_seconds': 720,
    },
    {
        'title': 'Fibonacci Sequence',
        'slug': 'level-27',
        'description': 'Print the first 7 Fibonacci numbers: 0, 1, 1, 2, 3, 5, 8.',
        'initial_code': '# Fibonacci\n',
        'test_code': 'assert "0" in output and "1" in output and "2" in output and "3" in output and "5" in output and "8" in output',
        'order': 27,
        'xp_reward': 50,
        'target_time_seconds': 720,
    },
    {
        'title': 'Anagram Check',
        'slug': 'level-28',
        'description': 'Check if "listen" and "silent" are anagrams.',
        'initial_code': 'word1 = "listen"\nword2 = "silent"\n',
        'test_code': 'assert "True" in output',
        'order': 28,
        'xp_reward': 50,
        'target_time_seconds': 720,
    },
    {
        'title': 'Binary Search',
        'slug': 'level-29',
        'description': 'Implement binary search to find 7 in [1, 3, 5, 7, 9]. Return the index.',
        'initial_code': 'arr = [1, 3, 5, 7, 9]\ntarget = 7\n',
        'test_code': 'assert "3" in output',
        'order': 29,
        'xp_reward': 50,
        'target_time_seconds': 900,
    },
    {
        'title': 'Bubble Sort',
        'slug': 'level-30',
        'description': 'Sort [64, 34, 25, 12, 22] using bubble sort.',
        'initial_code': 'arr = [64, 34, 25, 12, 22]\n',
        'test_code': 'assert arr == [12, 22, 25, 34, 64] or sorted(arr) == [12, 22, 25, 34, 64]',
        'order': 30,
        'xp_reward': 50,
        'target_time_seconds': 900,
    },
    {
        'title': 'Merge Two Lists',
        'slug': 'level-31',
        'description': 'Merge [1, 3, 5] and [2, 4, 6] into a single sorted list.',
        'initial_code': 'list1 = [1, 3, 5]\nlist2 = [2, 4, 6]\n',
        'test_code': 'assert "1" in output and "2" in output and "3" in output and "4" in output and "5" in output and "6" in output',
        'order': 31,
        'xp_reward': 50,
        'target_time_seconds': 900,
    },
    {
        'title': 'Two Sum',
        'slug': 'level-32',
        'description': 'Find two numbers in [2, 7, 11, 15] that sum to 9. Print their indices.',
        'initial_code': 'nums = [2, 7, 11, 15]\ntarget = 9\n',
        'test_code': 'assert ("0" in output and "1" in output) or ("1" in output and "0" in output)',
        'order': 32,
        'xp_reward': 50,
        'target_time_seconds': 900,
    },
    {
        'title': 'Valid Parentheses',
        'slug': 'level-33',
        'description': 'Check if "()()" has valid parentheses. Print True or False.',
        'initial_code': 's = "()()"\n',
        'test_code': 'assert "True" in output',
        'order': 33,
        'xp_reward': 50,
        'target_time_seconds': 900,
    },
    {
        'title': 'Longest Word',
        'slug': 'level-34',
        'description': 'Find the longest word in "The quick brown fox jumps".',
        'initial_code': 'sentence = "The quick brown fox jumps"\n',
        'test_code': 'assert "quick" in output or "brown" in output or "jumps" in output',
        'order': 34,
        'xp_reward': 50,
        'target_time_seconds': 720,
    },
    {
        'title': 'Character Frequency',
        'slug': 'level-35',
        'description': 'Count the frequency of each character in "hello".',
        'initial_code': 'text = "hello"\n',
        'test_code': 'assert "h" in output and "e" in output and "l" in output and "o" in output',
        'order': 35,
        'xp_reward': 50,
        'target_time_seconds': 720,
    },
    {
        'title': 'Matrix Transpose',
        'slug': 'level-36',
        'description': 'Transpose the matrix [[1, 2], [3, 4]] to [[1, 3], [2, 4]].',
        'initial_code': 'matrix = [[1, 2], [3, 4]]\n',
        'test_code': 'assert "[[1, 3], [2, 4]]" in str(output) or (len(output.strip()) > 0)',
        'order': 36,
        'xp_reward': 50,
        'target_time_seconds': 900,
    },
    {
        'title': 'GCD Calculator',
        'slug': 'level-37',
        'description': 'Calculate the GCD of 48 and 18.',
        'initial_code': 'a = 48\nb = 18\n',
        'test_code': 'assert "6" in output',
        'order': 37,
        'xp_reward': 50,
        'target_time_seconds': 720,
    },
    {
        'title': 'LCM Calculator',
        'slug': 'level-38',
        'description': 'Calculate the LCM of 12 and 15.',
        'initial_code': 'a = 12\nb = 15\n',
        'test_code': 'assert "60" in output',
        'order': 38,
        'xp_reward': 50,
        'target_time_seconds': 720,
    },
    {
        'title': 'Armstrong Number',
        'slug': 'level-39',
        'description': 'Check if 153 is an Armstrong number (1³ + 5³ + 3³ = 153).',
        'initial_code': 'n = 153\n',
        'test_code': 'assert "True" in output',
        'order': 39,
        'xp_reward': 50,
        'target_time_seconds': 780,
    },
    {
        'title': 'Perfect Number',
        'slug': 'level-40',
        'description': 'Check if 28 is a perfect number (sum of divisors equals the number).',
        'initial_code': 'n = 28\n',
        'test_code': 'assert "True" in output',
        'order': 40,
        'xp_reward': 50,
        'target_time_seconds': 780,
    },
    
    # ADVANCED (41-53): Complex algorithms, data structures
    {
        'title': 'Quick Sort',
        'slug': 'level-41',
        'description': 'Implement quicksort for [10, 7, 8, 9, 1, 5].',
        'initial_code': 'arr = [10, 7, 8, 9, 1, 5]\n',
        'test_code': 'assert sorted([10, 7, 8, 9, 1, 5]) == [1, 5, 7, 8, 9, 10]',
        'order': 41,
        'xp_reward': 50,
        'target_time_seconds': 1200,
    },
    {
        'title': 'Binary Tree Traversal',
        'slug': 'level-42',
        'description': 'Implement inorder traversal of a binary tree.',
        'initial_code': '# Binary tree traversal\n',
        'test_code': 'assert True  # Manual verification',
        'order': 42,
        'xp_reward': 50,
        'target_time_seconds': 1200,
    },
    {
        'title': 'Linked List',
        'slug': 'level-43',
        'description': 'Create a simple linked list with nodes [1, 2, 3].',
        'initial_code': '# Linked list\n',
        'test_code': 'assert True  # Manual verification',
        'order': 43,
        'xp_reward': 50,
        'target_time_seconds': 1200,
    },
    {
        'title': 'Stack Implementation',
        'slug': 'level-44',
        'description': 'Implement a stack with push, pop, and peek operations.',
        'initial_code': 'class Stack:\n    pass\n',
        'test_code': 'assert True  # Manual verification',
        'order': 44,
        'xp_reward': 50,
        'target_time_seconds': 1200,
    },
    {
        'title': 'Queue Implementation',
        'slug': 'level-45',
        'description': 'Implement a queue with enqueue and dequeue operations.',
        'initial_code': 'class Queue:\n    pass\n',
        'test_code': 'assert True  # Manual verification',
        'order': 45,
        'xp_reward': 50,
        'target_time_seconds': 1200,
    },
    {
        'title': 'DFS Graph Traversal',
        'slug': 'level-46',
        'description': 'Implement depth-first search for a graph.',
        'initial_code': '# DFS\n',
        'test_code': 'assert True  # Manual verification',
        'order': 46,
        'xp_reward': 50,
        'target_time_seconds': 1200,
    },
    {
        'title': 'BFS Graph Traversal',
        'slug': 'level-47',
        'description': 'Implement breadth-first search for a graph.',
        'initial_code': '# BFS\n',
        'test_code': 'assert True  # Manual verification',
        'order': 47,
        'xp_reward': 50,
        'target_time_seconds': 1200,
    },
    {
        'title': 'Longest Common Subsequence',
        'slug': 'level-48',
        'description': 'Find LCS of "ABCDGH" and "AEDFHR".',
        'initial_code': 's1 = "ABCDGH"\ns2 = "AEDFHR"\n',
        'test_code': 'assert "3" in output or "ADH" in output',
        'order': 48,
        'xp_reward': 50,
        'target_time_seconds': 1200,
    },
    {
        'title': 'Knapsack Problem',
        'slug': 'level-49',
        'description': 'Solve 0/1 knapsack: weights=[1,2,3], values=[10,15,40], capacity=5.',
        'initial_code': 'weights = [1, 2, 3]\nvalues = [10, 15, 40]\ncapacity = 5\n',
        'test_code': 'assert "55" in output or "50" in output',
        'order': 49,
        'xp_reward': 50,
        'target_time_seconds': 1500,
    },
    {
        'title': 'N-Queens Problem',
        'slug': 'level-50',
        'description': 'Solve the 4-Queens problem.',
        'initial_code': 'n = 4\n',
        'test_code': 'assert True  # Manual verification',
        'order': 50,
        'xp_reward': 50,
        'target_time_seconds': 1800,
    },
    {
        'title': 'Sudoku Solver',
        'slug': 'level-51',
        'description': 'Implement a basic Sudoku solver.',
        'initial_code': '# Sudoku solver\n',
        'test_code': 'assert True  # Manual verification',
        'order': 51,
        'xp_reward': 50,
        'target_time_seconds': 1800,
    },
    {
        'title': 'Regex Matcher',
        'slug': 'level-52',
        'description': 'Implement basic regex matching for pattern "a*b".',
        'initial_code': 'pattern = "a*b"\ntext = "aaab"\n',
        'test_code': 'assert True  # Manual verification',
        'order': 52,
        'xp_reward': 50,
        'target_time_seconds': 1800,
    },
    {
        'title': 'Master Challenge',
        'slug': 'level-53',
        'description': 'Design a simple hash table with collision handling.',
        'initial_code': 'class HashTable:\n    pass\n',
        'test_code': 'assert True  # Congratulations!',
        'order': 53,
        'xp_reward': 100,
        'target_time_seconds': 2400,
    },
]
