LEVELS = [
    # STAGE 1: BASIC OPERATIONS (1-10)
    {
        'title': 'Hello Python',
        'slug': 'z2h-1',
        'description': 'Welcome to the Python Arena! Your first task is to define a function `say_hello()` that returns the string "Hello, Python!".',
        'initial_code': 'def say_hello():\n    # Your code here\n    pass\n',
        'test_code': 'assert say_hello() == "Hello, Python!"',
        'order': 1,
        'xp_reward': 50,
        'target_time_seconds': 120,
    },
    {
        'title': 'Variable Math',
        'slug': 'z2h-2',
        'description': 'Define a function `add_ten(n)` that takes a number and returns that number plus 10.',
        'initial_code': 'def add_ten(n):\n    pass\n',
        'test_code': 'assert add_ten(5) == 15\nassert add_ten(-10) == 0',
        'order': 2,
        'xp_reward': 50,
        'target_time_seconds': 120,
    },
    {
        'title': 'The Remainder',
        'slug': 'z2h-3',
        'description': 'Use the modulo operator (%) to return the remainder of `a` divided by `b`.',
        'initial_code': 'def get_remainder(a, b):\n    pass\n',
        'test_code': 'assert get_remainder(10, 3) == 1\nassert get_remainder(20, 5) == 0',
        'order': 3,
        'xp_reward': 50,
        'target_time_seconds': 120,
    },
    {
        'title': 'String Length',
        'slug': 'z2h-4',
        'description': 'Return the length of the given string `s` using the `len()` function.',
        'initial_code': 'def count_chars(s):\n    pass\n',
        'test_code': 'assert count_chars("Python") == 6\nassert count_chars("") == 0',
        'order': 4,
        'xp_reward': 50,
        'target_time_seconds': 120,
    },
    {
        'title': 'F-String Fusion',
        'slug': 'z2h-5',
        'description': 'Use an f-string to return "Player: [name], Score: [score]".',
        'initial_code': 'def format_score(name, score):\n    pass\n',
        'test_code': 'assert format_score("Kira", 100) == "Player: Kira, Score: 100"',
        'order': 5,
        'xp_reward': 60,
        'target_time_seconds': 150,
    },
    {
        'title': 'Type Detective',
        'slug': 'z2h-6',
        'description': 'Return the type of the variable `x` using the `type()` function.',
        'initial_code': 'def get_type(x):\n    pass\n',
        'test_code': 'assert "int" in str(get_type(5))\nassert "str" in str(get_type("hi"))',
        'order': 6,
        'xp_reward': 60,
        'target_time_seconds': 150,
    },
    {
        'title': 'Integer Casting',
        'slug': 'z2h-7',
        'description': 'Convert the string `s` into an integer and return it.',
        'initial_code': 'def to_int(s):\n    pass\n',
        'test_code': 'assert to_int("123") == 123\nassert isinstance(to_int("45"), int)',
        'order': 7,
        'xp_reward': 60,
        'target_time_seconds': 150,
    },
    {
        'title': 'Absolute Power',
        'slug': 'z2h-8',
        'description': 'Return the absolute value of `n` using `abs()`.',
        'initial_code': 'def make_positive(n):\n    pass\n',
        'test_code': 'assert make_positive(-5) == 5\nassert make_positive(3) == 3',
        'order': 8,
        'xp_reward': 60,
        'target_time_seconds': 150,
    },
    {
        'title': 'Exponentiation',
        'slug': 'z2h-9',
        'description': 'Return `base` raised to the power of `exp` using the `**` operator.',
        'initial_code': 'def power_of(base, exp):\n    pass\n',
        'test_code': 'assert power_of(2, 3) == 8\nassert power_of(5, 2) == 25',
        'order': 9,
        'xp_reward': 70,
        'target_time_seconds': 180,
    },
    {
        'title': 'Multiple Returns',
        'slug': 'z2h-10',
        'description': 'Return both the sum and the product of `a` and `b` as a tuple.',
        'initial_code': 'def sum_and_prod(a, b):\n    pass\n',
        'test_code': 'assert sum_and_prod(3, 4) == (7, 12)\nassert sum_and_prod(10, 0) == (10, 0)',
        'order': 10,
        'xp_reward': 70,
        'target_time_seconds': 180,
    },

    # STAGE 2: DATA STRUCTURES (11-20)
    {
        'title': 'List Access',
        'slug': 'z2h-11',
        'description': 'Return the first element of the list `items`.',
        'initial_code': 'def get_first(items):\n    pass\n',
        'test_code': 'assert get_first([10, 20, 30]) == 10\nassert get_first(["a", "b"]) == "a"',
        'order': 11,
        'xp_reward': 80,
        'target_time_seconds': 200,
    },
    {
        'title': 'List Append',
        'slug': 'z2h-12',
        'description': 'Append the value `x` to the list `my_list` and return the modified list.',
        'initial_code': 'def add_item(my_list, x):\n    pass\n',
        'test_code': 'assert add_item([1, 2], 3) == [1, 2, 3]',
        'order': 12,
        'xp_reward': 80,
        'target_time_seconds': 200,
    },
    {
        'title': 'List Slicing',
        'slug': 'z2h-13',
        'description': 'Return the first 3 elements of the list `items`.',
        'initial_code': 'def get_top_three(items):\n    pass\n',
        'test_code': 'assert get_top_three([1, 2, 3, 4, 5]) == [1, 2, 3]',
        'order': 13,
        'xp_reward': 80,
        'target_time_seconds': 200,
    },
    {
        'title': 'Dictionary Lookup',
        'slug': 'z2h-14',
        'description': 'Given a dictionary `d` and a `key`, return the value associated with that key.',
        'initial_code': 'def find_value(d, key):\n    pass\n',
        'test_code': 'assert find_value({"a": 1, "b": 2}, "b") == 2',
        'order': 14,
        'xp_reward': 90,
        'target_time_seconds': 250,
    },
    {
        'title': 'Dictionary Update',
        'slug': 'z2h-15',
        'description': 'Add a new key-value pair to dictionary `d` and return it.',
        'initial_code': 'def update_dict(d, key, val):\n    pass\n',
        'test_code': 'res = update_dict({}, "id", 101)\nassert res["id"] == 101',
        'order': 15,
        'xp_reward': 90,
        'target_time_seconds': 250,
    },
    {
        'title': 'Unique Items',
        'slug': 'z2h-16',
        'description': 'Convert list `items` to a `set` to remove duplicates and return the set.',
        'initial_code': 'def get_unique(items):\n    pass\n',
        'test_code': 'assert get_unique([1, 1, 2, 3, 3]) == {1, 2, 3}',
        'order': 16,
        'xp_reward': 90,
        'target_time_seconds': 250,
    },
    {
        'title': 'Tuple Packing',
        'slug': 'z2h-17',
        'description': 'Return the arguments `x, y, z` packed into a tuple.',
        'initial_code': 'def pack_it(x, y, z):\n    pass\n',
        'test_code': 'assert pack_it(1, 2, 3) == (1, 2, 3)\nassert isinstance(pack_it(1,2,3), tuple)',
        'order': 17,
        'xp_reward': 100,
        'target_time_seconds': 300,
    },
    {
        'title': 'Counting Occurrences',
        'slug': 'z2h-18',
        'description': 'Use the `.count()` method to find how many times `val` appears in `items`.',
        'initial_code': 'def count_val(items, val):\n    pass\n',
        'test_code': 'assert count_val([1, 2, 2, 3], 2) == 2\nassert count_val("banana", "a") == 3',
        'order': 18,
        'xp_reward': 100,
        'target_time_seconds': 300,
    },
    {
        'title': 'Dictionary Keys',
        'slug': 'z2h-19',
        'description': 'Return a list of all keys in dictionary `d`.',
        'initial_code': 'def get_keys(d):\n    pass\n',
        'test_code': 'assert sorted(list(get_keys({"x": 1, "y": 2}))) == ["x", "y"]',
        'order': 19,
        'xp_reward': 100,
        'target_time_seconds': 300,
    },
    {
        'title': 'Clearing Lists',
        'slug': 'z2h-20',
        'description': 'Remove all items from `items` and return the empty list.',
        'initial_code': 'def clear_list(items):\n    pass\n',
        'test_code': 'assert clear_list([1, 2, 3]) == []',
        'order': 20,
        'xp_reward': 110,
        'target_time_seconds': 350,
    },

    # STAGE 3: CONTROL FLOW (21-30)
    {
        'title': 'Odd or Even',
        'slug': 'z2h-21',
        'description': 'Return "even" if `n` is divisible by 2, else "odd".',
        'initial_code': 'def check_parity(n):\n    pass\n',
        'test_code': 'assert check_parity(4) == "even"\nassert check_parity(7) == "odd"',
        'order': 21,
        'xp_reward': 120,
        'target_time_seconds': 400,
    },
    {
        'title': 'Grade Calculator',
        'slug': 'z2h-22',
        'description': 'Return "A" if score >= 90, "B" if >= 80, else "F".',
        'initial_code': 'def get_grade(score):\n    pass\n',
        'test_code': 'assert get_grade(95) == "A"\nassert get_grade(82) == "B"\nassert get_grade(50) == "F"',
        'order': 22,
        'xp_reward': 120,
        'target_time_seconds': 400,
    },
    {
        'title': 'Range Sum',
        'slug': 'z2h-23',
        'description': 'Return the sum of all numbers from 0 up to (but not including) `n` using `range()`.',
        'initial_code': 'def sum_range(n):\n    pass\n',
        'test_code': 'assert sum_range(5) == 10\nassert sum_range(10) == 45',
        'order': 23,
        'xp_reward': 120,
        'target_time_seconds': 400,
    },
    {
        'title': 'Find in List',
        'slug': 'z2h-24',
        'description': 'Return `True` if `target` is in `items`, else `False`.',
        'initial_code': 'def is_present(items, target):\n    pass\n',
        'test_code': 'assert is_present([1, 5, 9], 5) == True\nassert is_present([1, 5, 9], 2) == False',
        'order': 24,
        'xp_reward': 130,
        'target_time_seconds': 450,
    },
    {
        'title': 'Wholesale Loop',
        'slug': 'z2h-25',
        'description': 'Use a `while` loop to count how many times `n` can be divided by 2 before it is <= 1.',
        'initial_code': 'def count_divisions(n):\n    pass\n',
        'test_code': 'assert count_divisions(10) == 3\nassert count_divisions(100) == 6',
        'order': 25,
        'xp_reward': 130,
        'target_time_seconds': 450,
    },
    {
        'title': 'Short Circuit',
        'slug': 'z2h-26',
        'description': 'Return `True` if `a` is greater than 10 AND `b` is less than 5.',
        'initial_code': 'def complex_check(a, b):\n    pass\n',
        'test_code': 'assert complex_check(15, 2) == True\nassert complex_check(5, 2) == False',
        'order': 26,
        'xp_reward': 130,
        'target_time_seconds': 450,
    },
    {
        'title': 'List Comp: Squares',
        'slug': 'z2h-27',
        'description': 'Use a list comprehension to return squares of numbers in `nums`.',
        'initial_code': 'def get_squares(nums):\n    pass\n',
        'test_code': 'assert get_squares([1, 2, 3]) == [1, 4, 9]',
        'order': 27,
        'xp_reward': 140,
        'target_time_seconds': 500,
    },
    {
        'title': 'List Comp: Evens',
        'slug': 'z2h-28',
        'description': 'Use a list comprehension with an `if` to return only even numbers from `nums`.',
        'initial_code': 'def only_evens(nums):\n    pass\n',
        'test_code': 'assert only_evens([1, 2, 3, 4]) == [2, 4]',
        'order': 28,
        'xp_reward': 140,
        'target_time_seconds': 500,
    },
    {
        'title': 'Breaking Free',
        'slug': 'z2h-29',
        'description': 'Stop adding numbers from `nums` to a sum if the number 999 is encountered.',
        'initial_code': 'def sum_until_999(nums):\n    pass\n',
        'test_code': 'assert sum_until_999([1, 2, 999, 10]) == 3',
        'order': 29,
        'xp_reward': 150,
        'target_time_seconds': 550,
    },
    {
        'title': 'Continue Skipping',
        'slug': 'z2h-30',
        'description': 'Return the sum of `nums`, but skip any negative numbers.',
        'initial_code': 'def sum_positives(nums):\n    pass\n',
        'test_code': 'assert sum_positives([1, -5, 2, -10, 3]) == 6',
        'order': 30,
        'xp_reward': 150,
        'target_time_seconds': 550,
    },

    # STAGE 4: FUNCTIONS & SCOPE (31-40)
    {
        'title': 'Default Value',
        'slug': 'z2h-31',
        'description': 'Define `power(n, p=2)` where `p` defaults to 2.',
        'initial_code': 'def power(n, p=2):\n    pass\n',
        'test_code': 'assert power(3) == 9\nassert power(2, 3) == 8',
        'order': 31,
        'xp_reward': 160,
        'target_time_seconds': 600,
    },
    {
        'title': 'Factorial Recursion',
        'slug': 'z2h-32',
        'description': 'Implement factorial(n) recursively.',
        'initial_code': 'def factorial(n):\n    pass\n',
        'test_code': 'assert factorial(5) == 120\nassert factorial(0) == 1',
        'order': 32,
        'xp_reward': 160,
        'target_time_seconds': 600,
    },
    {
        'title': 'Global Access',
        'slug': 'z2h-33',
        'description': 'A global variable `COUNTER` exists. Increment it inside `increment_global()` and return it.',
        'initial_code': 'COUNTER = 0\ndef increment_global():\n    pass\n',
        'test_code': 'global COUNTER\nCOUNTER = 5\nassert increment_global() == 6',
        'order': 33,
        'xp_reward': 160,
        'target_time_seconds': 600,
    },
    {
        'title': 'Packing Args',
        'slug': 'z2h-34',
        'description': 'Use `*args` to return the count of arguments passed.',
        'initial_code': 'def count_args(*args):\n    pass\n',
        'test_code': 'assert count_args(1, 2, 3) == 3\nassert count_args() == 0',
        'order': 34,
        'xp_reward': 170,
        'target_time_seconds': 650,
    },
    {
        'title': 'Kwargs Dictionary',
        'slug': 'z2h-35',
        'description': 'Use `**kwargs` to return the dictionary of arguments.',
        'initial_code': 'def get_kwargs(**kwargs):\n    pass\n',
        'test_code': 'assert get_kwargs(a=1, b=2) == {"a": 1, "b": 2}',
        'order': 35,
        'xp_reward': 170,
        'target_time_seconds': 650,
    },
    {
        'title': 'Lambda Sort',
        'slug': 'z2h-36',
        'description': 'Sort a list of tuples `(name, age)` by age using a lambda as the key.',
        'initial_code': 'def sort_by_age(people):\n    pass\n',
        'test_code': 'data = [("A", 30), ("B", 20)]\nassert sort_by_age(data) == [("B", 20), ("A", 30)]',
        'order': 36,
        'xp_reward': 180,
        'target_time_seconds': 700,
    },
    {
        'title': 'Enumerate It',
        'slug': 'z2h-37',
        'description': 'Use `enumerate()` to return a list of tuples `(index, value)` from `items`.',
        'initial_code': 'def get_indexed(items):\n    pass\n',
        'test_code': 'assert get_indexed(["a", "b"]) == [(0, "a"), (1, "b")]',
        'order': 37,
        'xp_reward': 180,
        'target_time_seconds': 700,
    },
    {
        'title': 'Zip Together',
        'slug': 'z2h-38',
        'description': 'Use `zip()` to combine `names` and `scores` into a list of tuples.',
        'initial_code': 'def combine(names, scores):\n    pass\n',
        'test_code': 'assert combine(["Kira", "Finn"], [100, 90]) == [("Kira", 100), ("Finn", 90)]',
        'order': 38,
        'xp_reward': 180,
        'target_time_seconds': 700,
    },
    {
        'title': 'Map Multiplication',
        'slug': 'z2h-39',
        'description': 'Use `map()` and a lambda to multiply every number in `nums` by 10.',
        'initial_code': 'def multiply_map(nums):\n    pass\n',
        'test_code': 'assert list(multiply_map([1, 2])) == [10, 20]',
        'order': 39,
        'xp_reward': 190,
        'target_time_seconds': 750,
    },
    {
        'title': 'Filter Short Strings',
        'slug': 'z2h-40',
        'description': 'Use `filter()` to keep only strings longer than 3 characters.',
        'initial_code': 'def filter_long(strings):\n    pass\n',
        'test_code': 'assert list(filter_long(["hi", "python", "ok"])) == ["python"]',
        'order': 40,
        'xp_reward': 190,
        'target_time_seconds': 750,
    },

    # STAGE 5: STANDARD LIBRARY (41-45)
    {
        'title': 'Math PI',
        'slug': 'z2h-41',
        'description': 'Import `math` and return `math.pi`.',
        'initial_code': 'def share_pi():\n    pass\n',
        'test_code': 'import math\nassert share_pi() == math.pi',
        'order': 41,
        'xp_reward': 200,
        'target_time_seconds': 800,
    },
    {
        'title': 'Random Choice',
        'slug': 'z2h-42',
        'description': 'Import `random` and return a random item from `items`.',
        'initial_code': 'def get_random(items):\n    pass\n',
        'test_code': 'import random\nitems = [1, 2, 3]\nassert get_random(items) in items',
        'order': 42,
        'xp_reward': 200,
        'target_time_seconds': 800,
    },
    {
        'title': 'Exception Handling',
        'slug': 'z2h-43',
        'description': 'Return `a/b`, but if `ZeroDivisionError` occurs, return "Error".',
        'initial_code': 'def safe_divide(a, b):\n    pass\n',
        'test_code': 'assert safe_divide(10, 2) == 5\nassert safe_divide(10, 0) == "Error"',
        'order': 43,
        'xp_reward': 200,
        'target_time_seconds': 800,
    },
    {
        'title': 'Finally Cleanup',
        'slug': 'z2h-44',
        'description': 'Implement logic that sets `logger.status = "closed"` in a `finally` block.',
        'initial_code': 'def cleanup(logger):\n    try:\n        # Some work\n        pass\n',
        'test_code': 'class MockLogger: status = "open"\nl = MockLogger()\ncleanup(l)\nassert l.status == "closed"',
        'order': 44,
        'xp_reward': 220,
        'target_time_seconds': 850,
    },
    {
        'title': 'Context Lock',
        'slug': 'z2h-45',
        'description': 'Use a context manager `with lock:` to call `lock.action()` and return "Locked".',
        'initial_code': 'def use_lock(lock):\n    pass\n',
        'test_code': 'class MockLock:\n    def __enter__(self): return self\n    def __exit__(self, *a): pass\n    def action(self): self.called = True\nl = MockLock()\nassert use_lock(l) == "Locked"\nassert l.called == True',
        'order': 45,
        'xp_reward': 220,
        'target_time_seconds': 850,
    },

    # STAGE 6: OOP MASTERY (46-53)
    {
        'title': 'Class Creation',
        'slug': 'z2h-46',
        'description': 'Create a class `Warrior` with no specific attributes.',
        'initial_code': 'class Warrior:\n    pass\n',
        'test_code': 'w = Warrior()\nassert isinstance(w, Warrior)',
        'order': 46,
        'xp_reward': 300,
        'target_time_seconds': 900,
    },
    {
        'title': 'The Constructor',
        'slug': 'z2h-47',
        'description': 'Add an `__init__` method to `Pet` that sets `self.name`.',
        'initial_code': 'class Pet:\n    pass\n',
        'test_code': 'p = Pet("Fluffy")\nassert p.name == "Fluffy"',
        'order': 47,
        'xp_reward': 300,
        'target_time_seconds': 900,
    },
    {
        'title': 'Instance Methods',
        'slug': 'z2h-48',
        'description': 'Add a method `bark()` to `Dog` class that returns "Woof!".',
        'initial_code': 'class Dog:\n    def __init__(self, name):\n        self.name = name\n',
        'test_code': 'd = Dog("Rex")\nassert d.bark() == "Woof!"',
        'order': 48,
        'xp_reward': 350,
        'target_time_seconds': 1000,
    },
    {
        'title': 'Inheritance Base',
        'slug': 'z2h-49',
        'description': 'Create `Bird` class, then `Penguin` that inherits from `Bird`.',
        'initial_code': 'class Bird:\n    pass\n',
        'test_code': 'p = Penguin()\nassert isinstance(p, Bird)',
        'order': 49,
        'xp_reward': 350,
        'target_time_seconds': 1000,
    },
    {
        'title': 'Method Overriding',
        'slug': 'z2h-50',
        'description': 'Override `speak()` in `Cat` to return "Meow", while `Animal` returns "Unknown".',
        'initial_code': 'class Animal:\n    def speak(self): return "Unknown"\n',
        'test_code': 'c = Cat()\nassert c.speak() == "Meow"',
        'order': 50,
        'xp_reward': 400,
        'target_time_seconds': 1100,
    },
    {
        'title': 'Dunder Str',
        'slug': 'z2h-51',
        'description': 'Implement `__str__` in `User` to return its `username`.',
        'initial_code': 'class User:\n    def __init__(self, username):\n        self.username = username\n',
        'test_code': 'u = User("admin")\nassert str(u) == "admin"',
        'order': 51,
        'xp_reward': 400,
        'target_time_seconds': 1100,
    },
    {
        'title': 'Class Properties',
        'slug': 'z2h-52',
        'description': 'Use `@property` to create a read-only `full_name` by joining `first` and `last`.',
        'initial_code': 'class Human:\n    def __init__(self, first, last):\n        self.first = first\n        self.last = last\n',
        'test_code': 'h = Human("John", "Doe")\nassert h.full_name == "John Doe"',
        'order': 52,
        'xp_reward': 500,
        'target_time_seconds': 1200,
    },
    {
        'title': 'Abstraction',
        'slug': 'z2h-53',
        'description': 'Use `abc.ABC` and `abstractmethod` to define a `Tool` with an `operate()` method.',
        'initial_code': 'from abc import ABC, abstractmethod\n\nclass Tool(ABC):\n    pass\n',
        'test_code': 'import inspect\nassert inspect.isabstract(Tool)',
        'order': 53,
        'xp_reward': 1000,
        'target_time_seconds': 1800,
    },
]
